### ISSUE TITLE
readme has wrong link to releases

### ISSUE THREAD

**Issue by iProdigy** [JesseVii/StockScreener#1]
readme should link to https://github.com/JesseVii/StockScreener/releases rather than https://github.com/JesseVii/TTS/releases

**Comment by JesseVii** [comment]
Thanks! fixed it

**Comment by iProdigy** [comment]
Unrelated but do you happen to have time to look through https://github.com/JesseVii/TTS/pulls ? I also sent you a discord DM if you prefer to communicate over that channel
